# Generated by Django 2.2.5 on 2020-01-02 15:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
