# Generated by Django 2.2.5 on 2020-01-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneybook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(choices=[('en', 'USD'), ('kr', 'KRW'), ('eu', 'EUR')], default='kr', max_length=2)),
                ('category', models.CharField(blank=True, choices=[('ea', 'EAT'), ('ti', 'TICKET')], max_length=2)),
                ('memo', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
