# Generated by Django 2.2.5 on 2019-12-30 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneybook',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cores.TimeStampedModel')),
            ],
            bases=('cores.timestampedmodel',),
        ),
    ]
