# Generated by Django 2.2.5 on 2019-12-30 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneybooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneybook',
            name='category',
            field=models.CharField(blank=True, choices=[('ea', 'EAT'), ('ti', 'TICKET')], max_length=2),
        ),
        migrations.AddField(
            model_name='moneybook',
            name='companion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moneybook',
            name='currency',
            field=models.CharField(choices=[('en', 'USD'), ('kr', 'KRW'), ('eu', 'EUR')], default='kr', max_length=2),
        ),
        migrations.AddField(
            model_name='moneybook',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moneybook',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
